### ISSUE TITLE
Memory Leaks?

### ISSUE THREAD

**Issue by EmmanVazz** [xamarin/Xamarin.Forms.CarouselView#16]
Is anyone experiencing leaks of the children when using Carousel Views? I think it is related to this [bug](https://github.com/xamarin/Xamarin.Forms/pull/524#issuecomment-266188801) however I wanted to see if other people had workarounds.

Thanks!

**Comment by Motaz-Al-Zoubi** [comment]
I am suffering from memory leaks issues with the carousel view control in Xamarin forms,
the emulator keeps throwing out of memory exception while looping through the slides.
is this a common issue with this control or there is something i should figure out,
any help please?

**Comment by EmmanVazz** [comment]
I ran across this https://forums.xamarin.com/discussion/comment/243673?utm_campaign=Weekly%2BXamarin&utm_medium=email&utm_source=Weekly_Xamarin_116 . It seems like they will fix it in 2.4.0, which should be released in February. So I guess we will have to wait till then.

**Comment by Motaz-Al-Zoubi** [comment]
Any update on this issue?

**Comment by JRC-BitBull** [comment]
Yeah, I seem to be getting memory leaks with items placed in a CarouselView. Really interested whether anyone has any workarounds!

**Comment by shoeIT** [comment]
the workaround is to use the controll which works fine and is still under developement:
https://github.com/alexrainman/CarouselView

**Comment by JRC-BitBull** [comment]
I am using the latest version of that control and it leaks memory with Image objects on Android.

I managed to create a pretty hacky workaround that doesn't leak...

The DataTemplate in CarouselView is my own custom class that is a Subclass of Grid, call it MyDataTemplate. When one of these is added to a parent view ( OnSizeAllocated ) I perform a recursive callback to figure out the parent page and register the DataTemplate with the parent page.

When I am sure I don’t need the page any more I loop through all the registered MyDataTemplate instances and call a FreeMemory() method on them, this removes all the children from the Grid (including the Image instances) and seems to prevent any memory leaks.

**Comment by paul-kiar** [comment]
Since this project is closed but I need to use it, I have reworked [this PR](https://github.com/xamarin/Xamarin.Forms.CarouselView/pull/13) as a Patch that can be used by just copying [this code](https://gist.github.com/paul-kiar/4ca352a3add70d548742291441dc9873) into your Client project
