### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by hardcodet** [xamarin/Xamarin.Forms.CarouselView#17]
This control seems to be nearly done, but doesn't seem to be under development anymore. A quick status update would be great...

Thanks, Philipp

**Comment by EmmanVazz** [comment]
I ran across this https://forums.xamarin.com/discussion/comment/243673?utm_campaign=Weekly%2BXamarin&utm_medium=email&utm_source=Weekly_Xamarin_116 . It seems like they are working on it in 2.4.0, which should be released in February.

**Comment by Dids** [comment]
Pushed to Q2, from what I hear.

**Comment by less0** [comment]
Any news on that? Seems pretty abandoned to me!?

**Comment by hardcodet** [comment]
This has been abandoned in favor of https://github.com/alexrainman/CarouselView/
